apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: boardgame-hpa
  namespace: webapps
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: boardgame-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 85
